main_app/urls.py
from django.urls import path
from . import views

app_name = 'main_app'
# ルーティング自体に名前をつける　逆引きの際に使用

urlpatterns = [
    path('', views.IndexView.as_view(), name="index"),
    # viewsのIndexViewに処理を渡す 逆引きの際にnameを利用する as_viewsとすることでクラスベースのビューを関数化する

    path('inquiry/', views.InquiryView.as_view(), name="inquiry"),
    path('diary_list/', views.DiaryListView.as_view(), name="diary_list"),
    path('diary_detail/<int:pk>/', views.DiaryDetailView.as_view(), name="diary_detail"),
    path('diary_create/', views.DiaryCreateView.as_view(), name="diary_create"),
    path('diary_update/<int:pk>/', views.DiaryUpdateView.as_view(), name="diary_update"),
    path('diary_delete/<int:pk>/', views.DiaryDeleteView.as_view(), name="diary_delete"),
]

portfolio/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import static
from django.urls import path, include
from . import settings

# 各アプリのurls.pyの場所を記述する
urlpatterns = [
    path('control/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('allauth.urls')),
]

# 開発環境だけDjangoでメディアファイルを静的配信
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.contrib.auth.models import AbstractUser

class CustomUser(AbstractUser):
    """拡張ユーザーモデル"""

    class Meta:
        verbose_name_plural = 'CustomUser'

main_app/models.py
from accounts.models import CustomUser
from django.db import models

# プライマリキーは自動でid intengerに決まる
class Diary(models.Model):
    """日記モデル"""
    
    user = models.ForeignKey(CustomUser, verbose_name='ユーザー', on_delete=models.PROTECT)
    # 外部キー userで2つのテーブルを結びつける
    title = models.CharField(verbose_name='タイトル', max_length=40)
    content = models.TextField(verbose_name='本文', blank=True, null=True)
    photo1 = models.ImageField(verbose_name='写真1', blank=True, null=True)
    photo2 = models.ImageField(verbose_name='写真2', blank=True, null=True)
    photo3 = models.ImageField(verbose_name='写真3', blank=True, null=True)
    created_at = models.DateTimeField(verbose_name='作成日時', auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name='更新日時', auto_now=True)

    class Meta:
        verbose_name_plural = 'Diary'

    # titleを返す
    def __str__(self):
        return self.title

main_app/forms.py
from django.forms import Form, CharField, EmailField, Textarea, ModelForm
from django.core.mail import EmailMessage
from .models import Diary

# お問い合わせ用フォーム作成　4つのフィールドを定義
class InquiryForm(Form):
    name = CharField(label='お名前', max_length=30)
    email = EmailField(label='メールアドレス')
    title = CharField(label='タイトル', max_length=30)
    message = CharField(label='メッセージ', widget=Textarea)

    # Bootstrap用設定
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['name'].widget.attrs['class'] = 'form-control'
        self.fields['name'].widget.attrs['placeholder'] = 'お名前を入力してください。'

        self.fields['email'].widget.attrs['class'] = 'form-control'
        self.fields['email'].widget.attrs['placeholder'] = 'メールアドレスを入力してください。'

        self.fields['title'].widget.attrs['class'] = 'form-control'
        self.fields['title'].widget.attrs['placeholder'] = 'タイトルを入力してください。'

        self.fields['message'].widget.attrs['class'] = 'form-control'
        self.fields['message'].widget.attrs['placeholder'] = 'メッセージを入力してください。'

    # postされたデータを取得
    def send_email(self):
        name = self.cleaned_data['name']
        email = self.cleaned_data['email']
        title = self.cleaned_data['title']
        message = self.cleaned_data['message']

        subject = 'お問い合わせ{}'.format(title)
        message = '送信者名: {0}\nメールアドレス: {1}\nメッセージ:\n{2}'.format(name, email, message)
        from_email = 'admin@email.com'
        to_list = [
            'test@example.com'
        ]
        cc_list = [
            email
        ]

        message = EmailMessage(subject=subject, body=message, from_email=from_email, to=to_list, cc=cc_list)
        message.send()
        # sendメソッドで送信

# Modelを継承してFormが作れる
class DiaryCreateForm(ModelForm):
    class Meta:
        model = Diary
        fields = ('title', 'content', 'photo1', 'photo2', 'photo3')

accounts/views.py
from django.shortcuts import render

# Create your views here.

main_app/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, FormView, ListView, DetailView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Diary
from .forms import InquiryForm, DiaryCreateForm
# カレントディレクトリのforms.からimport

import logging

logger = logging.getLogger(__name__)
# ロガーを取得

class IndexView(TemplateView):
    template_name = "index.html"
    # 指定したテンプレートファイルをtemplatesディレクトリから探す

class InquiryView(FormView):
    template_name = "inquiry.html"
    form_class = InquiryForm
    # クラス関数：form_classをオーバーライド　formsで作成したInquiryFormを呼び出し
    success_url = reverse_lazy('main_app:inquiry')
    # 処理が問題ない時にリダイレクト　urlへ逆引き

    # フォームバリデーションに問題がなかったら（POSTされたら）実行される
    def form_valid(self, form):
        form.send_email()
        # メール送信メソッド実行
        messages.success(self.request, 'メッセージを送信しました。')
        # messagesメソッド　送信完了したことを通知
        return super().form_valid(form)
        # オーバーライドしたform_validを実行？　親クラスを実行する

class DiaryListView(ListView, LoginRequiredMixin):  #ログイン状態でないとアクセスできなくする
    template_name = "diary_list.html"
    model = Diary
    paginate_by = 3

    def get_queryset(self):
        tmp = Diary.objects.filter(user=self.request.user)
        diaries = tmp.order_by('-created_at')
        return diaries
    # ログインユーザーの投稿を持ってくる
    # filter 検索条件を指定
    # 作成順に並べ替え

class DiaryDetailView(DetailView, LoginRequiredMixin):
    template_name = "diary_detail.html"
    model = Diary

class DiaryCreateView(CreateView, LoginRequiredMixin):
    template_name = "diary_create.html"
    model = Diary
    form_class = DiaryCreateForm
    # 自作のFormを(読み込み)オーバーライド
    success_url = reverse_lazy('main_app:diary_list')
    # 処理が完了した際の遷移先を指定

    # formのバリデーションに問題がないとき実行される
    def form_valid(self, form):
        diary = form.save(commit=False)
        # DBにフォーム内容を保存する前にモデルオブジェクト(Diary)を取得して、値を代入する
        diary.user = self.request.user
        # ログインuserを自動で取得する
        diary.save()
        # 最後にDBへ保存
        messages.success(self.request, "日記を作成しました")
        return super().form_valid(form)

    # バリデーション失敗時に実行される
    def form_invalid(self, form):
        messages.error(self.request, "日記の作成に失敗しました")
        return super().form_invalid(form)


class DiaryUpdateView(UpdateView, LoginRequiredMixin):
    template_name = "diary_update.html"
    model = Diary
    form_class = DiaryCreateForm

    # 処理完了後の遷移先　動的に変化するurlを記述　キーを渡す
    def get_success_url(self):
        return reverse_lazy('main_app:diary_detail', kwargs={'pk': self.kwargs['pk']})

    def form_valid(self, form):
        messages.success(self.request, "日記を更新しました")
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, "日記の更新に失敗しました")
        return super().form_invalid(form)

class DiaryDeleteView(DeleteView, LoginRequiredMixin):
    template_name = 'diary_delete.html'
    model = Diary
    success_url = reverse_lazy('main_app:diary_list')

    # 削除成功時に実行されるメソッドにmessagesをオーバーライド
    def delete(self, request, *args, **kwargs):
        messages.success(self.request, "日記が削除されました")
        return super().delete(request, *args, **kwargs)

main_app/templates/base.html
{% load static %}
<!-- staticタグを利用できるように記載 -->

<html lang="ja">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block title %}{% endblock %}</title>
    <!-- タイトルを埋め込み -->

     <!-- Bootstrap Core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- staticファイルのパスを相対パスで記述 -->

    <!-- Custom Fonts -->
    <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">
    <link href="{% static 'vendor/simple-line-icons/css/simple-line-icons.css' %}" rel="stylesheet">
    <!-- Custom CSS -->
    <link href="{% static 'css/stylish-portfolio.min.css' %}" rel="stylesheet">
    {% block head %}{% endblock %}
</head>

<body id="page-top">
      <!-- Navigation -->
    <a class="menu-toggle rounded" href="#">
        <i class="fas fa-bars"></i>
    </a>
    <nav id="sidebar-wrapper">
        <ul class="sidebar-nav">
        <li class="sidebar-brand">
            <a class="js-scroll-trigger" href="{% url 'main_app:index' %}">My Portfolio</a>
            <!-- URLタグ view->urls main_appアプリのurlsでindexを参照する -->
        </li>
        <li class="sidebar-nav-item">
            <a class="js-scroll-trigger" href="{% url 'main_app:index' %}#page-top">Home</a>
        </li>
        {% if user.is_authenticated %}
        <li class="sidebar-nav-item">
            <a class="js-scroll-trigger" href="{% url 'main_app:diary_list' %}">Diary list</a>
        </li>
        <li class="sidebar-nav-item">
            <a class="js-scroll-trigger" href="{% url 'account_logout' %}">Log out</a>
        </li>
        {% else %}
        <li class="sidebar-nav-item">
            <a class="js-scroll-trigger" href="{% url 'account_signup' %}">Sign up</a>
        </li>
        <li class="sidebar-nav-item">
            <a class="js-scroll-trigger" href="{% url 'account_login' %}">Log in</a>
        </li>
        {% endif %}
        <li class="sidebar-nav-item">
            <a class="js-scroll-trigger" href="{% url 'main_app:inquiry' %}">Inquiry</a>
        </li>
        </ul>
    </nav>
    
    <!-- messages（変数）があったらリストをループさせ表示させる -->
    {% if messages %}
    <div class="container">
        <div class="row">
            <div class="my-div-style w-100">
                <ul class="messages" style="list-style: none;">
                    {% for message in messages %}
                    <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>
                        {{ message }}
                    </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
    {% endif %}

    {% block contents %}{% endblock %}

    <hr>
    <footer class="footer text-center">
        <div class="container">
            <ul class="list-inline mb-5">
                <li class="list-inline-item">
                    <a class="social-link rounded-circle text-white mr-3" href="https://www.facebook.com/">
                        <i class="icon-social-facebook"></i>
                    </a>
                </li>
                <li class="list-inline-item">
                    <a class="social-link rounded-circle text-white mr-3" href="https://twitter.com/">
                        <i class="icon-social-twitter"></i>
                    </a>
                </li>
                <li class="list-inline-item">
                    <a class="social-link rounded-circle text-white" href="https://github.com/h1r08a/portfolio">
                        <i class="icon-social-github"></i>
                    </a>
                </li>
            </ul>
            <p class="text-muted small mb-0">Copyright &copy; Your Website 2020</p>
        </div>
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Plugin JavaScript -->
    <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Custom scripts for this template -->
    <script src="{% static 'js/stylish-portfolio.min.js' %}"></script>

</body>

</html>

main_app/templates/diary_create.html
{% extends 'base.html' %}
{% block title %}Diary create{% endblock %}

{% block contents %}
<section class="content-section">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
                <!-- 画像ファイルを送信可能にする -->
                <form method="POST" enctype="multipart/form-data"> 
                    {% csrf_token %}
                    <table class="table">
                        {{ form.as_table }}
                    </table>
                    <button class="btn btn-primary" type="submit">作成</button>
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock %}

main_app/templates/diary_delete.html
{% extends 'base.html' %}
{% block title %}Diary delete{% endblock %}

{% block contents %}
<section class="content-section">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
                <form method="POST"> 
                    {% csrf_token %}
                    <p>本当に削除しますか？</p>
                    <button class="btn btn-primary" type="submit">削除</button>
                    <a class="btn btn-secondary" href="{% url 'main_app:diary_detail' object.pk %}">キャンセル</a>
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock %}

main_app/templates/diary_detail.html
{% extends 'base.html' %}
{% block title %}Diary detail{% endblock %}

<!-- viewsが操作しているオブジェクトobject -->
{% block contents %}
<section class="content-section">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
                <div class="post-heading">
                    <h2 class="post-title">{{ object.title }}</h2>
                    <span class="meta">Created at {{ object.created_at }}</span>
                    <br>
                    <span class="meta">Updated at {{ object.updated_at }}</span>
                </div>
                <hr>
                <div>
                    {{ object.content | urlize | linebreaksbr }}
                </div>
                {% if object.photo1 %}
                <hr>
                <!-- pathしかDBに保存されていないからurlをつける -->
                <img src="{{ object.photo1.url }}" width="100%" height="auto" alt="{{ object.photo1 }}"> 
                {% endif %}
                {% if object.photo2 %}
                <hr>
                <!-- pathしかDBに保存されていないからurlをつける -->
                <img src="{{ object.photo2.url }}" width="100%" height="auto" alt="{{ object.photo2 }}"> 
                {% endif %}
                {% if object.photo3 %}
                <hr>
                <!-- pathしかDBに保存されていないからurlをつける -->
                <img src="{{ object.photo3.url }}" alt="{{ object.photo3 }}"> 
                {% endif %}
                <hr>
                <a class="btn btn-primary" href="{% url 'main_app:diary_update' object.pk %}">編集</a>
                <a class="btn btn-secondary" href="{% url 'main_app:diary_delete' object.pk %}">削除</a>
            </div>
        </div>
    </div>
</section>
{% endblock %}

main_app/templates/diary_list.html
{% extends 'base.html' %}
{% block title %}Diary list{% endblock %}

{% block contents %}
<section class="content-section">
    <div class="container"><h1>Diary List</h1>
        <a class="btn btn-primary" href="{% url 'main_app:diary_create' %}">新規作成</a>
    </div>
{% for diary in diary_list %}
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
                <div class="post-preview">
                    <!-- urlにモデルのid(pk)を送っている　逆引き　diary.pk:モデルからidを引っ張ってきているだけ -->
                    <a href="{% url 'main_app:diary_detail' diary.pk %}">
                        <h2 class="post-title">
                            {{ diary.title }}
                        </h2>
                        <h4 class="post-subtitle">
                            {{ diary.content|truncatechars:30 }}
                        </h4>
                    </a>
                    <p class="post-meta">{{ diary.created_at }}</p>
                </div>
            </div>
        </div>
    </div>
    <hr>
    {% empty %}
        <p>日記が存在しません。</p>
    {% endfor %}

    {% if is_paginated %}
        {% include 'pagination.html' %}
    {% endif %}
</section>
{% endblock %}

main_app/templates/diary_update.html
{% extends 'base.html' %}
{% block title %}Diary update{% endblock %}

{% block contents %}
<section class="content-section">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
                <!-- 画像ファイルを送信可能にする -->
                <form method="POST" enctype="multipart/form-data"> 
                    {% csrf_token %}
                    <table class="table">
                        {{ form.as_table }}
                    </table>
                    <button class="btn btn-primary" type="submit">更新</button>
                    <a class="btn btn-secondary" href="{% url 'main_app:diary_detail' object.pk %}">キャンセル</a>
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock %}

main_app/templates/index.html
{% extends 'base.html' %}
<!-- base.htmlにblockタグを埋め込むためのextends -->

{% load static %}
<!-- staticファイルの場所を記述 -->

{% block title %}MyPortfolio{% endblock %}

{% block contents %}
<!-- top -->
<section class="masthead d-flex">
    <div class="container text-center my-auto">
        <h1 class="mb-1">My Portfolio</h1>
        <h3 class="mb-5">
            <em>日記管理サービスを作成しました！</em>
        </h3>
        <a class="btn btn-primary btn-xl js-scroll-trigger" href="#about">この作品について</a>
        <a class="btn btn-primary btn-xl" href="{% url 'account_login' %}">日記サイトへGO</a>
    </div>
    <div class="overlay"></div>
</section>

<!-- About -->
<section class="content-section bg-light" id="about">
    <div class="container text-center">
        <div class="row">
            <div class="col-lg-10 mx-auto">
                <h2>この作品について</h2>
                <h3>Web上で記事の作成・編集・削除ができる日記管理サービスを作成しました</h3>
                <p class="lead mb-5">フロントエンドのHTML/CSS/JSのベースは
                    <a href="https://startbootstrap.com/">Start Bootstrap</a>を使用しています</p>
                <a class="btn btn-dark btn-xl js-scroll-trigger" href="#services">機能一覧</a>
            </div>
        </div>
    </div>
</section>

<!-- Services -->
<section class="content-section bg-primary text-white text-center" id="services">
    <div class="container">
        <div class="content-section-heading">
            <h3 class="text-secondary mb-0">Services</h3>
            <h2 class="mb-5">機能一覧</h2>
        </div>
        <div class="row">
            <div class="col-lg-3 col-md-6 mb-5 mb-lg-0">
                <span class="service-icon rounded-circle mx-auto mb-3">
                    <i class="icon-star"></i>
                </span>
                <h4>
                    <strong>日記機能</strong>
                </h4>
                <p class="text-faded mb-0">投稿 / 編集 / 削除<br>詳細表示<br>一覧表示(ページネーション)</p>
            </div>
            <div class="col-lg-3 col-md-6 mb-5 mb-lg-0">
                <span class="service-icon rounded-circle mx-auto mb-3">
                    <i class="icon-diamond"></i>
                </span>
                <h4>
                    <strong>会員機能</strong>
                </h4>
                <p class="text-faded mb-0">管理ユーザーの<br>サインアップ / ログイン</p>
            </div>
            <div class="col-lg-3 col-md-6 mb-5 mb-md-0">
                <span class="service-icon rounded-circle mx-auto mb-3">
                    <i class="icon-ghost"></i>
                </span>
                <h4>
                    <strong>画像ファイル</strong>
                </h4>
                <p class="text-faded mb-0">アップロード機能</p>
            </div>
            <div class="col-lg-3 col-md-6">
                <span class="service-icon rounded-circle mx-auto mb-3">
                    <i class="icon-mustache"></i>
                </span>
                <h4>
                    <strong>問合せ機能</strong>
                </h4>
                <p class="text-faded mb-0">問合せ機能</p>
            </div>
        </div>
    </div>
</section>

<!-- Call to Action -->
<section class="content-section bg-primary text-white">
    <div class="container text-center">
        <h2 class="mb-4">以下のボタンをクリックして使用技術を確認してください</h2>
        <a href="#technology" class="btn btn-xl btn-dark js-scroll-trigger">技術 / サービス</a>
    </div>
</section>

<!-- Portfolio -->
<section class="content-section" id="technology">
    <div class="container">
        <div class="content-section-heading text-center">
            <h3 class="text-secondary mb-0">Technology</h3>
            <h2 class="mb-5">技術 / サービス</h2>
        </div>
        <div class="row no-gutters">
            <div class="col-lg-6">
                <a class="portfolio-item" href="https://www.python.jp/index.html">
                    <div class="caption">
                        <div class="caption-content">
                            <div class="h2">Python</div>
                            <p class="mb-0">
                                Python 3.7.6<br>
                                Django 2.2.2<br>
                            </p>
                        </div>
                    </div>
                    <img class="img-fluid" src="{% static 'img/1.jpg' %}" alt="">
                </a>
            </div>
            <div class="col-lg-6">
                <a class="portfolio-item" href="https://www.postgresql.jp/">
                    <div class="caption">
                        <div class="caption-content">
                            <div class="h2">PostgreSQL</div>
                            <p class="mb-0">PostgreSQL 10.4</p>
                        </div>
                    </div>
                    <img class="img-fluid" src="{% static 'img/2.jpg' %}" alt="">
                </a>
            </div>
            <div class="col-lg-6">
                <a class="portfolio-item" href="https://aws.amazon.com/jp/">
                    <div class="caption">
                        <div class="caption-content">
                            <div class="h2">AWS</div>
                            <p class="mb-0">VPC, EC2, S3, RDS, Route53, ACM, ELB
                            </p>
                        </div>
                    </div>
                    <img class="img-fluid" src="{% static 'img/3.jpg' %}" alt="">
                </a>
            </div>
            <div class="col-lg-6">
                <a class="portfolio-item" href="https://www.docker.com/">
                    <div class="caption">
                        <div class="caption-content">
                            <div class="h2">Docker</div>
                            <p class="mb-0">（勉強中）</p>
                        </div>
                    </div>
                    <img class="img-fluid" src="{% static 'img/4.jpg' %}" alt="">
                </a>
            </div>
            <div class="container text-center">
                <br>
                <a class="btn btn-primary btn-xl" href="{% url 'account_login' %}">日記サイトへGO</a>
            </div>
        </div>
    </div>
</section>

<!-- Scroll to Top Button-->
<a class="scroll-to-top rounded js-scroll-trigger" href="#page-top">
    <i class="fas fa-angle-up"></i>
</a>
{% endblock %}

main_app/templates/inquiry.html
{% extends 'base.html' %}
{% block title %}お問い合わせ{% endblock %}

{% block contents %}
<section class="content-section">
    <div class="container">
        <h1>Inquiry</h1>
        <div class="row">
            <form method="post">
                <!-- self.cleaned_data　に格納される -->
                {% csrf_token %}
                {{ form.non_field_error }}
                <!-- 特定のフィールドに紐づかないエラーを表示 -->
                {% for field in form %}
                <div class="form-group row">
                    <label for="{{ field.id_for_label }}" class="col-sm-4 col-form-label">
                        <strong>{{ field.label_tag }}</strong>
                    </label>
                    <div class="col-sm-8">
                        {{ field }}
                        {{ field.errors }}
                        <!-- フィールド単位のエラーを表示 -->
                    </div>
                </div>
                {% endfor %}

                <div class="offset-sm-4 col-ms-8">
                    <button class="btn btn-primary" type="submit" disabled>送信</button>
                </div>
            </form>
        </div>
    </div>
</section>
{% endblock %}

main_app/templates/pagination.html
<nav aria-label="Page navigation">
    <ul class="pagination justify-content-center">
        
        <!-- 前ページへのリンク -->
        {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
                <span class="sr-only">Previous</span>
            </a>
        </li>
        {% endif %}

        <!-- ページ数表示 -->
        {% for num in paginator.page_range %}
        {% if page_obj.number == num %}
        <li class="page-item active">
            <span class="page-link">
                {{ num }}
                <span class="sr-only">(current)</span>
            </span>
        </li>
        {% else %}
        <li class="page-item">
            <a class="page-link" href="?page={{ num }}">{{ num }}</a>
        </li>
        {% endif %}
        {% endfor %}

        <!-- 次ページへのリンク -->
        {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
                <span class="sr-only">Next</span>
            </a>
        </li>
        {% endif %}
        
    </ul>
</nav>